import { useState } from 'react'
import { Card } from '../components/ui.jsx'
import { positions as defaultPositions } from '../data/mockData.js'

export function ExposureChart({ positions = [] }) {
  if (positions.length === 0) {
    return <p className="empty-state">No positions to chart.</p>
  }

  const max = Math.max(...positions.map((p) => Math.abs(p.unrealized)), 0)

  return (
    <div className="bar-chart">
      {positions.map((p) => {
        const pct = max === 0 ? 0 : Math.round((Math.abs(p.unrealized) / max) * 100)
        return (
          <div className="bar-row" key={p.symbol}>
            <span className="bar-label mono">{p.symbol}</span>
            <div className="bar-track">
              <div
                className={p.unrealized >= 0 ? 'bar-fill bar-pos' : 'bar-fill bar-neg'}
                style={{ width: `${pct}%` }}
              />
            </div>
            <span className={p.unrealized >= 0 ? 'value-pos bar-value' : 'value-neg bar-value'}>
              {p.unrealized >= 0 ? '+' : ''}
              {p.unrealized.toFixed(0)}
            </span>
          </div>
        )
      })}
    </div>
  )
}

export function answerCopilotQuery(query, positions) {
  const trimmed = query.trim()
  if (!trimmed) {
    return null
  }
  if (positions.length === 0) {
    return "There are no positions in the portfolio right now, so there's nothing to report on."
  }

  const top = positions.reduce((best, p) => (p.unrealized > best.unrealized ? p : best), positions[0])

  return (
    `(Mock response) Based on current positions, your largest unrealized P&L contributor ` +
    `is ${top.symbol} at ${top.unrealized >= 0 ? '+' : ''}$${top.unrealized.toLocaleString()}. ` +
    `In the real system this answer is generated by the Reporting & Charting Agent's ` +
    `NL-query copilot over live portfolio data (workplan.md §6–7), not invented by the model.`
  )
}

export default function Reporting() {
  const [query, setQuery] = useState('')
  const [answer, setAnswer] = useState(null)

  function askCopilot(e) {
    e.preventDefault()
    const response = answerCopilotQuery(query, defaultPositions)
    if (response) setAnswer(response)
  }

  return (
    <div className="page">
      <div className="page-head">
        <h1>Reporting &amp; Charting</h1>
        <p className="page-lede">
          Scheduled and ad hoc reports, plus an NL-query copilot over portfolio/risk data
          (workplan.md §6).
        </p>
      </div>

      <Card title="Unrealized P&amp;L by Position">
        <ExposureChart positions={defaultPositions} />
      </Card>

      <Card title="Ask the Research Copilot" subtitle="Mocked for now — reads only, never invents numbers">
        <form className="copilot-form" onSubmit={askCopilot}>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="e.g. What's my largest position by unrealized P&L?"
            aria-label="Ask the research copilot"
          />
          <button type="submit">Ask</button>
        </form>
        {answer && (
          <div className="copilot-answer" role="status">
            {answer}
          </div>
        )}
      </Card>
    </div>
  )
}
