import { useState } from 'react'
import { Card } from '../components/ui.jsx'
import { positions } from '../data/mockData.js'

function ExposureChart() {
  const max = Math.max(...positions.map((p) => Math.abs(p.unrealized)))
  return (
    <div className="bar-chart">
      {positions.map((p) => {
        const pct = Math.round((Math.abs(p.unrealized) / max) * 100)
        return (
          <div className="bar-row" key={p.symbol}>
            <span className="bar-label mono">{p.symbol}</span>
            <div className="bar-track">
              <div
                className={p.unrealized >= 0 ? 'bar-fill bar-pos' : 'bar-fill bar-neg'}
                style={{ width: `${pct}%` }}
              />
            </div>
            <span className={p.unrealized >= 0 ? 'value-pos bar-value' : 'value-neg bar-value'}>
              {p.unrealized >= 0 ? '+' : ''}
              {p.unrealized.toFixed(0)}
            </span>
          </div>
        )
      })}
    </div>
  )
}

export default function Reporting() {
  const [query, setQuery] = useState('')
  const [answer, setAnswer] = useState(null)

  function askCopilot(e) {
    e.preventDefault()
    if (!query.trim()) return
    setAnswer(
      `(Mock response) Based on current positions, your largest unrealized P&L contributor ` +
        `is AAPL at +$${positions[0].unrealized.toLocaleString()}. In the real system this ` +
        `answer is generated by the Reporting & Charting Agent's NL-query copilot over live ` +
        `portfolio data (workplan.md §6–7), not invented by the model.`,
    )
  }

  return (
    <div className="page">
      <div className="page-head">
        <h1>Reporting &amp; Charting</h1>
        <p className="page-lede">
          Scheduled and ad hoc reports, plus an NL-query copilot over portfolio/risk data
          (workplan.md §6).
        </p>
      </div>

      <Card title="Unrealized P&amp;L by Position">
        <ExposureChart />
      </Card>

      <Card title="Ask the Research Copilot" subtitle="Mocked for now — reads only, never invents numbers">
        <form className="copilot-form" onSubmit={askCopilot}>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="e.g. What's my largest position by unrealized P&L?"
          />
          <button type="submit">Ask</button>
        </form>
        {answer && <div className="copilot-answer">{answer}</div>}
      </Card>
    </div>
  )
}
